name: Conference Workflow
on:
  schedule:
    - cron: "0 0 * * 0" # This will run the workflow every Sunday at midnight
  push:
    branches:
      - "**/issue**"
  issues:
    types: [opened, closed, edited, deleted]
  workflow_dispatch:

jobs:
  conference-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install PyGithub PyYAML pre-commit

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          python _conferences
          pre-commit run --all-files --show-diff-on-failure

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update conferences" || exit 0
          git push
